[package]
name = "cmac"
version = "0.2.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Generic implementation of Cipher-based Message Authentication Code"
documentation = "https://docs.rs/cmac"
repository = "https://github.com/RustCrypto/MACs"
keywords = ["crypto", "mac", "cmac", "omac"]
categories = ["cryptography", "no-std"]

[dependencies]
crypto-mac = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
block-cipher-trait = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
dbl = "0.2"

[dev-dependencies]
#crypto-mac = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx", features = ["dev"] }
#aes = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
